### ISSUE TITLE
Dynamic import not detected when code is instrumented by ember-cli-code-coverage

### ISSUE THREAD

**Issue by JoelWAnna** [ef4/ember-auto-import#116]
example repo https://github.com/JoelWAnna/wasm-example#master
run with `COVERAGE=true ember s` . Analyzer#parseImports fails to identify the dynamic import

workaround is to add the file(s) with dynamic imports to the `excludes: []` config for ember-cli-code coverage

**Comment by ef4** [comment]
Thanks for a thorough bug report.

**Comment by jrjohnson** [comment]
This bit me pretty hard and in a confusing way since the files were just missing from our deployment when it was packaged in Travis. Would this be worth adding to the README or is it too much of an edge case? I'm happy to open a PR.

**Comment by ef4** [comment]
Sorry about that. Your comment caused me to bubble this issue up in priority and check out the original reproduction.

ember-cli-code-coverage was doing some very weird stuff and this was their bug. They were actually replacing all source files with the text "undefined" before passing them onward to other plugins like ember-auto-import.

I say "was" because it looks like ember-cli-code-coverage's 1.0 betas no longer have this bug. I tested with v1.0.0-beta.8 and it plays nice with auto-import. Maybe try upgrading to the beta, and filing an issue on ember-cli-code-coverage to warn people about this incompatibility until the beta is released.

**Comment by jrjohnson** [comment]
No problem! No need to change the docs here then and I'll investigate updating to beta and testing.  Thanks.
