### ISSUE TITLE
Is it possible to work around code that expects globals? 

### ISSUE THREAD

**Issue by jacobq** [ef4/ember-auto-import#147]
See example repo here: https://github.com/jacobq/auto-import-demo

After playing with this, I don't think it's a problem with `ember-auto-import`; it's more a question about how to deal with existing code that expects globals to be present. I read the [FAQ entry about `jQuery` plugins](https://github.com/ef4/ember-auto-import#im-trying-to-load-a-jquery-plugin-but-it-doesnt-attach-itself-to-the-copy-of-jquery-thats-already-in-my-ember-app), which is similar but not quite the same. Rather than tell webpack that it should use a global (presumed to be present at run-time) instead of providing it, I want to do the reverse: tell it that a package should be made global for another package. 

Specifically, I ran into this problem while trying to bring in PouchDB's in-memory plugin. That code [immediately checks for the presence of a global `PouchDB` object](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb/src/plugins/memory.js#L10). Although I was able to work around this by using a variant of this code instead (via separate [`pouchdb-adapter-memory`](https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-adapter-memory) package), I would like to know if I could have made the other code work with `ember-auto-import` / `webpack`. Would I need to do something [like this](https://stackoverflow.com/questions/37656592/define-global-variable-with-webpack#40416826)?

Feel free to close if this is too much out of scope.

**Comment by ef4** [comment]
If PouchDb sets itself as a global, you can import for side effect and as long as you do the imports in order it will all work:

```
// creates window.PouchDB
import 'pouchdb';

// can consume window.PouchDB
import thing from 'pouchdb-adapter-memory';
```

On the other hand, if `PouchDB` is actually behaving better as a module and _doesn't_ set itself as a global, you can set the global yourself. But since all `imports` run before any other code in a module, you need to make a separate helper module:

```
import "./setup-pouchdb-global";
import thing from 'pouchdb-adapter-memory';
```

```
// setup-pouchdb-global
import PouchDB from 'pouchdb';
window.PouchDB = PouchDB;
```

In the second case, you can do the same thing with webpack's provider plugin. In your own Ember app that is probably fine, in an addon I tend to caution people to rely less on customized webpack config because it doesn't compose nicely from many sources.

**Comment by jacobq** [comment]
Thanks for your prompt and detailed answer. It was helpful to me. Part of my confusion seems to be coming from the state of the PouchDB community. Their most recent release changes a lot of things and it wasn't clear to me as a newcomer which docs were obsolete and which were current.
