### ISSUE TITLE
Idea: fail build if peerDep is missing?

### ISSUE THREAD

**Issue by samselikoff** [ef4/ember-auto-import#186]
In an effort to improve our community's larger dependency issues, I was wondering if Auto Import could do some general-purpose build-time validation & failure.

I was thinking that Auto Import could fail a build if a `peerDependency` is specified but not found in the host app. This is more or less the behavior I would expect at the npm/tooling level, but because it is not enforced, we could consider adding that ourselves. Then addon authors in the Ember ecosystem would be encouraged to use `peerDependencies` more, and it might make everyone's lives a little easier.

Many addons code this sort of thing manually today. It seems like it could be easily shared, either in a separate project, or in this one.

**Comment by ef4** [comment]
There is an [open ember-cli RFC](https://github.com/ember-cli/rfcs/pull/112) about this (though the document seems to be in limbo due to the migration from ember-cli/rfcs to emberjs/rfcs).

As far as I know, auto-import will already fail the build if you're trying to import a peerDependency that isn't present.

As a general lint, I think this feature would belong in https://github.com/quaertym/ember-cli-dependency-checker

**Comment by samselikoff** [comment]
Interesting, I'm not familiar with ember-cli-dependency-checker... Is this widely used? I don't use npm shrinkwrap – should I be? Does this affect the peerDependency discussion?

**Comment by ef4** [comment]
> I'm not familiar with ember-cli-dependency-checker... Is this widely used?

You're almost certainly using it in every Ember app you touch. It's part of the default app and addon blueprints.

> I don't use npm shrinkwrap – should I be?

Absolutely not, it's terrible, which is why even NPM had to eventually admit it and create package-lock.json instead.

The README is just spending a weird amount of ink on that feature because the README is a bit stale. It really has nothing fundamental to do with ember-cli-dependency-checker. The point is that every time you see something like this out of ember-cli:

```
Missing yarn packages:
Package: a-dependency
  * Specified: *
  * Installed: (not installed)

Run `yarn` to install missing dependencies.
```

That message is coming from ember-cli-dependency-checker.

**Comment by samselikoff** [comment]
Ah, I gotcha - didn't know that! Does seem like the right place for it then.
