### ISSUE TITLE
How to exclude ember-auto-import if a dependency includes it as a dependency?

### ISSUE THREAD

**Issue by Gaurav0** [ef4/ember-auto-import#195]
ember-cli-plotly is bringing in ember-auto-import as a dependency. This includes plotly, which I already include separately. Furthermore, ember-auto-import then tries to import lots of other things, which spew errors and break my build. How can I prevent it from being included?

**Comment by buschtoens** [comment]
One possible solution would be that ember-cli-plotly should make plotly a peerDependency instead of a direct dependency as per https://github.com/ef4/ember-auto-import/issues/170#issuecomment-449123743.

**Comment by Gaurav0** [comment]
This isn't what is being recommended in the README and it seems a lot of addons are adding ember-auto-import as a dependency.

**Comment by ef4** [comment]
> Furthermore, ember-auto-import then tries to import lots of other things

auto-import is supposed to be scoped per package. Just because one addon is using it doesn't mean that the app or any other addon will start getting auto-imports. What other things are getting pulled into your app? Where are they imported from?

If you run a build with `DEBUG=ember-auto-import:*` and share the results that may help.

> it seems a lot of addons are adding ember-auto-import as a dependency

It's correct to have ember-auto-import as a dependency. Jan was talking about plotly, not ember-auto-import. It is sometimes a good idea to make something like plotly a peerDependency, because that gives the consuming app more control over exactly which version will be used and can guarantee that it will be shared between both the app and the addon.

Also, answering a question you asked in Discord:
> can I blacklist a  package that is a dependency of an addon in ember-cli-build.js?

I think the answer is yes, but at the moment it would require you to add ember-auto-import to your app's own devDependencies. I assume you don't want to do that, since not wanting your stuff auto-imported is the whole context of this issue. 

So I filed https://github.com/ef4/ember-auto-import/issues/196 to correct this. I agree that an app should be able to alter the auto-import configuration even when it is only some addons that directly depend on auto-import.

**Comment by Gaurav0** [comment]
So I thought that d3 and numeral we're being imported from my app but it turns out they are also dependencies of plotly, so perhaps this is why they are being imported a second time and breaking. I'll try to make a reproduction tomorrow to see if this theory is correct.

**Comment by Gaurav0** [comment]
Sorry, forgot I left this open. Since March, I've no longer had access to the repo where I had experienced this problem.
