### ISSUE TITLE
Importing 'uuid' module errors

### ISSUE THREAD

**Issue by knownasilya** [ef4/ember-auto-import#20]
Getting this error during build:

```
Path must be a string. Received { './lib/rng.js': './lib/rng-browser.js',
  './lib/sha1.js': './lib/sha1-browser.js',
  './lib/md5.js': './lib/md5-browser.js' }
```

Using v0.2.1

**Comment by ef4** [comment]
Thanks, we didn't account for the possibility that the `browser` field in package.json is allowed to hold a POJO.

Probably the best solution is to not try to replicate any of that logic and just feed a shim file into webpack so it will deal with the resolution for us. I was already experimenting with that in order to get smaller builds, too (it's likely better if we can feed all of our external deps to webpack in a single run rather than package up each library separately).

**Comment by mhluska** [comment]
@ef4 can you explain more on how to resolve this? I'm getting this issue with the [sanity-io/client](https://github.com/sanity-io/sanity/blob/02e5dba450c9a6608ccb330b275b5624fb0b51ec/packages/%40sanity/client/package.json#L19) project.

**Comment by ef4** [comment]
If you want to have a go at fixing this, it's a reasonably focused change. After some more experimentation, the thing I said above is close but not exactly right.

We will still need to do our own entrypoint discovery (because we want to make each lookup relative to the addon or app that's doing the import, and then run webpack a single time to capture all the external dependencies). But we don't need to reimplement the entrypoint logic because it's available in https://github.com/webpack/enhanced-resolve.

We would refactor [this function](https://github.com/ef4/ember-auto-import/blob/19f75881cae56902b1a88eae9f13479d22f15a72/lib/dep-finder.js#L50-L63) to use enhanced-resolve, with the option `mainFields: ['browser', 'module', 'main']`. The `lookupStartPath` you'd pass to enhanced-resolve is `this._project.root`. The function signature would also change so that it gets the complete import path, instead of the separated `name` and `innerPath`, because we would just pass the whole import path to enhanced-resolve and let it handle the details.
