### ISSUE TITLE
[bug] 1.4.0 introduces "global is not defined"

### ISSUE THREAD

**Issue by jasonmit** [ef4/ember-auto-import#218]
As of 1.4.0, Webpack no longer is polyfilling `global`.

This was spotted in my [CI pipeline](https://travis-ci.org/ember-intl/ember-intl/jobs/541087407#L697) for ember-intl.  Other users also reported seeing this on other libs that `ember-auto-import` bundles i.e, [`auth0-lock`](https://github.com/ember-intl/ember-intl/issues/891).

I believe the issue was introduced here: https://github.com/ef4/ember-auto-import/pull/216

If `node: false` is recommended then I'd suggest a new major version and reverted for 1.x branch.

A workaround for now:
https://github.com/ember-intl/ember-intl/commit/f0419f29e51cbbb0337203de9cd09dba3998b87e#diff-168726dbe96b3ce427e7fedce31bb0bc

**Comment by ef4** [comment]
The problem is that doing a major doesn't really help you. Only one copy of ember-auto-import is allowed to win, and if the app has one, it will be that one. So as soon as apps upgrade, ember-intl would break again in the same way.

I do consider #216 a bugfix. Automatically polyfilling node behaviors for the browser was never intentional. `global` is not valid Javascript in browsers. I'm sorry this is likely to break things for people who were accidentally relying on the bug.

I agree that the situation with webpack configs is not ideal. Unfortunately they don't compose well, and most settings are extremely global in nature. So it's hard for addons to change settings without having big side effects. But that is why I think it's so important to have defaults that try to adhere as closely as possible to web standards, without sneaking in implementation-defined things like webpack's polyfills.

Thankfully `global` is quite easy to polyfill directly. Before importing the library that uses `global`, you can import your own module that says `window.global = window`.

**Comment by jasonmit** [comment]
Ah, I forgot about the single add-on limitation.  Embroide won't suffer from this, correct?  It sounds like a one off polyfill then is more reliable solution then modifying the unified webpack config.

Thanks a ton for the quick response, feel free to close.

**Comment by Driezzz** [comment]
@ef4 
> I'm sorry this is likely to break things for people who were accidentally relying on the bug.

This does break indeed, but how can we fix this error? Where do I put window.global = window?
`ReferenceError: global is not defined`
