### ISSUE TITLE
Importing from urls

### ISSUE THREAD

**Issue by knownasilya** [ef4/ember-auto-import#223]
Seems like services like https://www.pika.dev/cdn are getting more popular and people are using urls more for importing modules, e.g.

```
import {Component, render} from 'https://cdn.pika.dev/preact/v8';
```

Should urls work with auto-import sync and async?

**Comment by ef4** [comment]
There's nothing in our architecture that precludes this, and the adoption of the V2 Addon format will let Ember Addons be consumed through Pika.

But I I am skeptical about Pika being a good fit for any app that plans to have a long life and grow many features. Once you go beyond a very simple app, it's going to underperform having a build step. [Pika's own docs](https://www.pika.dev/blog/pika-web-a-future-without-webpack#the-pika-web-app-strategy) basically admit this. Pika's premise is: custom bundler configuration is hard and expensive, so put it off until later. Ember's premise is: custom bundler configuration is hard and expensive, so use the shared community out-of-the-box solution.

As far as I can tell, they have no solution to the problem that `yarn.lock` or `package-lock.json` solves.

**Comment by Frank3K** [comment]
We're some years later now and dynamic imports are pretty well supported now ([mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)).

I agree with the above comment on bundling packages from external services like Pika (now Skypack). For our use case we would like to dynamically import some ESM module that we have created ourselves. Because we do not know compile-time which module we should load and whether the user is actually going to use the functionality, we want to load it on demand using the `import()` syntax. But this does not seem yet possible using ember-auto-import. When we try to include it like this it throws an error:

```js
	const url = 'http://localhost:8000/code.js';
	const { object1, object2 } = await import(url);
```

This throws with:

```bash
 import() is only allowed to contain string literals or template string literals
```

It does work as follows:

```js
	const { object1, object2 } = await import('http://localhost:8000/code.js');
```

Which is fine if the URL is static, but that's not the case for our scenario.

In webpack, there's the _webpackIgnore_ comment that can be used on dynamic import ([docs](https://webpack.js.org/api/module-methods/#magic-comments)), which would solve this issue from what I understand. But it does not seem to be propagated by ember-auto-import.

What would be your advice to handle scenarios like this?

**Comment by ef4** [comment]
This was implemented a long time ago. The issue is stale.

The only requirement is that the protocol prefix is static so we can prove it's definitely a URL. See a big list of legal cases here in the tests:

https://github.com/ef4/ember-auto-import/blob/24896d3d38b948dcc9126df9203a3e7cd10506e1/packages/ember-auto-import/ts/tests/splitter-test.ts#L270-L281

**Comment by Frank3K** [comment]
Cool! Thanks for quick response and link to the related tests. It was not clear to me by reading the README and error that this was possible.

For reference: it has been added in https://github.com/ef4/ember-auto-import/pull/331.
