### ISSUE TITLE
Can no longer import isomorphic-git

### ISSUE THREAD

**Issue by knownasilya** [ef4/ember-auto-import#224]
```
ERROR in ./node_modules/globalyzer/src/index.js
Module not found: Error: Can't resolve 'path' in '/Users/ilya/sandbox/branch/node_modules/globalyzer/src'
 @ ./node_modules/globalyzer/src/index.js 1:13-28
 @ ./node_modules/isomorphic-git/dist/for-future/isomorphic-git/index.js
 @ /private/var/folders/hq/m0d3mb8s5gd1wdbn_gsk55000000gn/T/broccoli-919189mGQgcEuEM0v/cache-228-bundler/staging/app.js
 @ multi /private/var/folders/hq/m0d3mb8s5gd1wdbn_gsk55000000gn/T/broccoli-919189mGQgcEuEM0v/cache-228-bundler/staging/l.js /private/var/folders/hq/m0d3mb8s5gd1wdbn_gsk55000000gn/T/broccoli-919189mGQgcEuEM0v/cache-228-bundler/staging/app.jsBuild Error (Bundler)

webpack returned errors to ember-auto-import


Stack Trace and Error Report: /var/folders/hq/m0d3mb8s5gd1wdbn_gsk55000000gn/T/error.dump.f8c0d592d763e6f58e768429a46559fb.log
```

**Comment by ef4** [comment]
`path` is a node-only, built-in package.

We had a bug where we were accidentally providing automatic polyfills for that and several other node built-in packages, but we fixed the bug. And unfortunately due to the "only one copy must win" nature of ember-auto-import, there's not much way to gracefully roll out this bugfix (apps and addons can all update independently and all of them must be prepared to deal with the new version taking over). Sorry it bit you. See also previous https://github.com/ef4/ember-auto-import/issues/218#issuecomment-500539712

You can affirmatively add the polyfill like:

```js
autoImport: {
  webpack: { 
    node: { 
      path: true 
    }
}
```

**Comment by knownasilya** [comment]
Ah, I was hoping this was the issue. Thanks
