### ISSUE TITLE
Superfluous default keys importing firebase

### ISSUE THREAD

**Issue by dcyriller** [ef4/ember-auto-import#241]
I'm using `ember-auto-import` to load firebase (esm version) in an app:
```
import * as firebase from "firebase/app";
```

Inspecting `firebase` imported module, it looks like this:
```
{
  INTERNAL: {...},
  ...,
  default: {
      INTERNAL: {...},
      ...,
      default: {
          INTERNAL: {...},
          ...,
          default: {
              .... and so on
          }
      }
  }
}
```

As you can see, default is recursively included in child keys.

Is it a known issue, a bug or am I missing something with the dependency?

## versions

`ember-source@3.12.0` && `ember-auto-import@1.5.2` && `firebase@6.6.2`

`ember-cli-build.js`:
```
    autoImport: {
      skipBabel: [
        { package: 'firebase' },
      ],
    },

```

**Comment by ef4** [comment]
I think you're not getting the esm version, you're probably getting the cjs.  `firebase/app/package.json` says:

```
  "main": "dist/index.cjs.js",
  "browser": "dist/index.cjs.js",
  "module": "dist/index.esm.js",
```

Our priority order follows the webpack default, which is

1. browser
2. module
3. main

So browser wins, and we use the cjs version. Which means there will be some CJS/ESM interop code involved.

But probably it doesn't matter. The data structure can't really be infinitely deep, what you're seeing is the same object over and over again, because it has a property pointing at itself.

```js
import * as firebase from 'firebase/app';
console.log(firebase.default === firebase.default.default.default);
// true
```

**Comment by dcyriller** [comment]
> The data structure can't really be infinitely deep, what you're seeing is the same object over and over again, because it has a property pointing at itself.

I didn’t know that. Thank you for the explanation. It looks like it’s not really an issue then. I’m closing.
