### ISSUE TITLE
High vulnerability in dependencies

### ISSUE THREAD

**Issue by cythrawll** [ef4/ember-auto-import#242]
Both `handlebars` and `braces` (which is included by broccoli) have high vulnerability CVE open against them.  handlebars in particular is causing issues as it is a dependency and causing audit failures in builds.  Also `ember-try` is pulling in a vulnerable version of `lodash`

handlebars:
https://npmjs.com/advisories/1164 

braces:
https://npmjs.com/advisories/786

lodash:
https://npmjs.com/advisories/1065
https://npmjs.com/advisories/782
https://npmjs.com/advisories/577

**Comment by caljess599** [comment]
"handlebars": "~4.1.2" needs to be updated to >=4.3.0   to resolve the Prototype Pollution vulnerability.

**Comment by ef4** [comment]
FWIWl, these audits are quite dubious, and you should challenge whoever is doing them for you to explain the vulnerability, because I doubt they can, because I doubt there's a real one here.

Prototype pollution in handlebars only matters if you are passing untrusted input to handlebars templates. But ember-auto-import doesn't do that. It only runs at build time, and the only inputs it sees are whatever your developers give it.

This is a general issue bigger than ember-auto-import: it's super important to know which code runs in the browser vs in node at build time, and these audits aren't aware of the difference. It causes major misallocation of attention and resources.

I will still update eventually because there's no reason not to. But this is not a high-priority issue for me because there is no real vulnerability in ember-auto-import.
