### ISSUE TITLE
Running out of memory analyzing massive files

### ISSUE THREAD

**Issue by EWhite613** [ef4/ember-auto-import#268]
Would like a way to exclude folders (or include).

We have some massive mirage response files in our app. And from the `DEBUG=*` it looks like `ember-auto-import` is trying to analyze those files (resulting in a massive amount of babel logs that look to be parsing).

Followed my an out of memory error.

I know it's `ember-auto-import` because as soon as I remove that addon from the app I can build without issue.

**Comment by rwjblue** [comment]
FWIW, you can't really use `DEBUG=*` due to babel itself emitting so much output (it will often completely crash the process just emitting logging output).

I'd suggest using: `DEBUG=*,-babel`

**Comment by ef4** [comment]
If we're parsing the files, then so is babel and it manages to do it without running out of memory. That makes me wonder if we're retaining something unintentionally for too long.

I'm not sure about an option to ignore directories, because it would result in very confusing conditions when somebody later tries to use an import in an ignored directory and gets no feedback from ember-auto-import about why it won't work.

**Comment by EWhite613** [comment]
@ef4 isn't that just an "Uh duh" moment though?

Like babel also has ignore https://babeljs.io/docs/en/options#ignore I use to just ignore all the mirage files.

There is a warning from babel from all those files but still sound like. they parse it
```
Note: The code generator has deoptimised the styling of <path>/mirage/responses/ws_line_to_line_service-trails.js as it exceeds the max of 500KB
```

**Comment by ef4** [comment]
> I use to just ignore all the mirage files.
> There is a warning from babel

I'm pretty sure you're not successfully causing babel to ignore those files, both because it's still warning and because of how babel runs inside a broccoli pipeline, where the paths it sees are not the ones you authored.

**Comment by EWhite613** [comment]
With the newer auto-import, I didn't have this issue anymore
