### ISSUE TITLE
Support dynamic import from URL

### ISSUE THREAD

**Issue by jelhan** [ef4/ember-auto-import#276]
Current ember-auto-import enforces that dependency in a dynamic import is referenced by a static string. It throws otherwise.

```js
// supported
await import('highcharts');

// not supported
let dep = 'highcharts';
await import(dep);
```

This makes sense if the dependency is a local module. ember-auto-import needs to know at build-time what other module to include in the build.

But this also prevents us from referencing a precompiled dependency through an URL:

```js
let dep = 'http://examples.com/some-third-party-script.js';
await import(dep);
```

This seems to be a legitimate use case to me. We consider this approach to lazy-load web components at run-time depending on meta-data fetched from the backend. A simplified version of the code looks like this:

```js
let registeredComponent = this.store.find('registered-component', id);
let webComponent = await import(registeredComponent.url);
```

This seems to work fine in my tests as soon as we modify ember-auto-import to not throw but just skip the dynamic import if it's not a string:

```patch
diff --git a/node_modules/ember-auto-import/js/analyzer.js b/node_modules/ember-auto-import/js/analyzer.js
index 1868de2..8ae6c3a 100644
--- a/node_modules/ember-auto-import/js/analyzer.js
+++ b/node_modules/ember-auto-import/js/analyzer.js
@@ -157,7 +157,7 @@ class Analyzer extends broccoli_plugin_1.default {
                     // argument, so we can just assume this exists
                     let argument = path.node.arguments[0];
                     if (argument.type !== 'StringLiteral') {
-                        throw new Error('ember-auto-import only supports dynamic import() with a string literal argument.');
+                        return;
                     }
                     imports.push({
                         isDynamic: true,
```

**Comment by ef4** [comment]
We can certainly make this case work, but the thing I want to design carefully is making it difficult for people to accidentally fall into this code path when they didn't mean to.

One problem: if they're still trying to support a browser that doesn't have native `import()`, and we leave an `import()` in, the code will fail to parse and they're app won't even boot!

Another problem: there are some pretty natural things people might try that won't correctly. Like, you can start with this and it works the way you want it to:

```js
import('./thing');
```

And then you refactor it to this and you think it should still work:

```js
function whichThing(user) {
  if (user.allowed) {
    return './thing';
  } else {
    return './placeholder';
  }
}
import(whichThing(currentUser()));
```

But now you've accidentally opted into the runtime-only code path, because we can't statically tell what you're talking about. It's impossible for us to know that we need to build bundles for those two modules in particular. It might even work by accident if there's some other code in the app that dynamically imports both of them! But then later when that other code gets refactored away, this spot would mysteriously break.

One potential solution to this problem is that we can require a static prefix that makes it clear you're talking about a URL:

```js
import(`https://${this.webcomponent}`);
```

And since protocol-relative URLs are a thing, this would also be allowed:

```js
import(`//${this.webcomponent}`);
```

This has the nice property of also allowing you to statically restrict which domain you would load code from, which would limit the scope of some potentially damaging security bugs:

```js
import(`https://mydomain.com/${this.webcomponent}`);
```

**Comment by ef4** [comment]
I realize I didn't spell it out explicitly above: the reason a static prefix is good is that it lets us allow intentional runtime imports while also allowing us to keep the other example:

```js
import(whichThing(currentUser()));
```

as a build error.

**Comment by jelhan** [comment]
> One potential solution to this problem is that we can require a static prefix that makes it clear you're talking about a URL:
> 
> ```js
> import(`https://${this.webcomponent}`);
> ```
> 
> And since protocol-relative URLs are a thing, this would also be allowed:
> 
> ```js
> import(`//${this.webcomponent}`);
> ```

This sounds like a lot of additional complexity. Both in the implementation here as well as in the documentation. And I fear it makes some use cases way more complex than necessary. Imagine to see code like this:

```js
if (dep.startsWith('https://')) {
  import(`https://${dep.substr(8)}`);
} else {
  // relative URL
  import(`//${dep.substr(2)}`);
}
```

Did you considered adding an explicit opt out instead? Similar to `/* eslint-disable */`? Not sure how complex it is to implement but something like this might raise even more awareness while not restricting any usage:

```js
/* ember-auto-import-disable */
let dep = 'http://examples.com/some-third-party-script.js';
await import(dep);
/* ember-auto-import-enable */
```

> One problem: if they're still trying to support a browser that doesn't have native `import()`, and we leave an `import()` in, the code will fail to parse and they're app won't even boot!

We could detect this scenario at build time, couldn't we? Not sure how complex it is but as we know the build targets, we should know if any of them does not support `import()`. Actually we are just talking about IE11 here, aren't we?

**Comment by ef4** [comment]
> This sounds like a lot of additional complexity. 

It's not, though. It's less complexity than the viable alternatives. It uses only the semantics of Javascript as already defined. Options like a magic comment are more complex and more likely to break in the future or cause extra implementation burden because they rely on extra non-standard semantics.

I'm thinking about how to write code that will work forever, even under future build systems that don't exist yet or in future browsers that are optimized enough to not need bundling at all, or hybrids of both. At what stage do comments get stripped in those future worlds? Who knows, systems are free to strip them whenever they wants because that's what the language standard says. Do all the intermediate representations (ASTs, etc) in those systems accurately encode comment information? They aren't obligated to. And if instead of a comment we use some config that lives elsewhere in another file, that is even worse because now both human readers and compilers can't know what the code means without going elsewhere to read a config file, and "going elsewhere" can change meanings radically as you move between precompilation and runtime implementations.

Realize also that we're talking about a thing that can be a low-level primitive, not necessarily the final word on developer-facing API. Nobody needs to actually type out the substr stuff if they don't want to, it can go into one shared tiny library and they can say:

```js
import { importURL } from 'the-library';
importURL(myURL);
```

There *is* an alternative that's even simpler, but I don't think it seems viable. It would be to reserve `import()` to *always* mean a runtime import from a URL, and no build-time interpretation would *ever* be done. That is simpler and clear and causes no uncanny behavior that will trip up developers, but it requires us to invent our own macro to mean build-time-`import()`. I think it's not viable because it's out of step with how the rest of the JS ecosystem is already using `import()`, and it requires us to teach everybody a new concept up front -- whereas the teaching burden about which things you can `import()` only comes up the first time you try to say something too dynamic, in which case rather than failing cryptically we can give you very precise feedback about why the system can't understand you and your options for remedying that.

I should also be explicit here: ember-auto-import intends to exactly follow the semantics in https://github.com/emberjs/rfcs/pull/507, so this is really a discussion about how to extend that RFC, which is fine, but I'm not going to ship a feature in ember-auto-import that doesn't work exactly the same way in embroider, because ember-auto-import is basically a polyfill for embroider.

**Comment by jelhan** [comment]
Thanks a lot for your detailed answer.

> I should also be explicit here: ember-auto-import intends to exactly follow the semantics in [emberjs/rfcs#507](https://github.com/emberjs/rfcs/pull/507), so this is really a discussion about how to extend that RFC, which is fine, but I'm not going to ship a feature in ember-auto-import that doesn't work exactly the same way in embroider, because ember-auto-import is basically a polyfill for embroider.

Makes sense. Lets move the discussion to the RFC. Let me try to summarize what options we have discussed so far:

1. Support template literals if they start with `https://` or `//`.
   ```js
   import(`https://${this.webcomponent}`);
   import(`//${this.webcomponent}`);
   ```
2. Skip build-time transform with magic comments.
   ```js
   /* ember-auto-import-disable */
   await import(this.webcomponent);
   /* ember-auto-import-enable */
   ```
3. Reserve `import()` for runtime imports and add a dedicated build-time-`import()` macro.

These are low-level primitives. The developer-facing API might be different.

I see a potential fourth option that we did not discussed yet:

4. Add a lint rule forbidding dynamic imports. Silently skip dynamic imports at build-time and leave them untouched instead of throwing.

Do you want to open the discussion at RFC yourself? Otherwise I can try to do so. I don't feel comfortable enough with summarizing the arguments for each of that options. So I would just list what has been discussed so far and point the readers to this issue for details. If you have time to put there are more comprehensive summary as a starting point of the discussion, that would be awesome.

**Comment by jelhan** [comment]
This is supported by v2 Addon Format now: https://github.com/emberjs/rfcs/blob/master/text/0507-embroider-v2-package-format.md#supported-subset-of-dynamic-import-syntax
