### ISSUE TITLE
webpack NODE_ENV always set to production ?

### ISSUE THREAD

**Issue by rps-v** [ef4/ember-auto-import#296]
I'm trying to load the development version of `react`  but it seems that `process.env.NODE_ENV` is always set to `production`, no matter what webpack config or `ENV.environment` I set.

The `react.development.js` file gets loaded, however it has a check for `NODE_ENV` which fails

**NOTE:** I am running `ember s --env local`.

Any ideas how to solve this ?
Where is the best place to put the aliases (`alias`, `webpack.resolve.alias` or `webpack.resolveLoader.alias`) ?

Tried these in various combinations inside `ember-cli-build`:
```js
autoImport: {
			alias: {
				apexcharts: 'apexcharts/dist/apexcharts',
				'react': 'react/cjs/react.development',
			},
			webpack: {
				mode: 'development',
				optimization: {
					minimize: false,
					nodeEnv: 'development',
				},
				plugins: [
					new webpack.DefinePlugin({
						'process.env.NODE_ENV': 'development',
					})
				],
				resolveLoader: {
					alias: {
						'react': 'react/cjs/react.development',
					}
				},
				resolve: {
					alias: {
						'react': 'react/cjs/react.development',
					}
				}
			}
		},
```

**Comment by ef4** [comment]
I tried to reproduce this, but it all worked for me with no config. I confirmed that I get the production react build with `--env production` and the dev react build for any other value.

There must be something else in your app or dependencies that's manipulating NODE_ENV. 

Trying to use `--env local` might be triggering bugs in some other addon you have present. In general, [it's not safe](https://discuss.emberjs.com/t/impossible-to-minify-other-than-production/12117/12?u=ef4) to pass anything other than "development", "test", or "production" to ember-cli's `--env`, because other library code may see `env != "development"` and try to disable development features.

**Comment by rps-v** [comment]
Thank you very much for looking into this.

I tried `ember s` and it still used the production build of React, so it might be something else that causes this. Also, setting `NODE_ENV` environment variable does not override it - which is definitely strange.

Unfortunately, this is a rather large app and trying to remove every dependency to test which one might be the problem is not really feasible. If you have any ideas how to try and find what changes NODE_ENV, that would be really helpful.
