### ISSUE TITLE
Broken sourcemaps for vendor.js

### ISSUE THREAD

**Issue by Turbo87** [ef4/ember-auto-import#315]
The way we currently concatenate our content to the `vendor.js` file is breaking the sourcemap for `vendor.js`. This is becoming very visible when using something like Sentry (via `ember-auto-import`) to collect errors in the application and that decoding the sourcemaps.

What usually happens is that any stack frames that point to code from `ember-auto-import` instead point to the last line above all of the `ember-auto-import` content, which makes debugging quite a bit harder. 

I looked into maybe solving this via https://github.com/ef4/fast-sourcemap-concat, but that has an async API, which apparently doesn't play well with how we're currently concatenating things.

@ef4 any ideas?

**Comment by ef4** [comment]
The simplest thing would be to not concatenate anything, and instead add script tags for the entry chunks.

I didn't do that initially because I wasn't sure if it would break people's deployment setups. They need to know to upload the extra chunk files alongside their original app.js and vendor.js. And this can happen just because one of your addons starts using ember-auto-import, even if you didn't do anything in your app that would cause you to think your set of assets would change.

But if we think everyone is already uploading `assets/*.js`, then it's probably safe. We already have this same potential issue for lazy chunks, and I haven't heard any problems, but I'm sure lazy chunks are less frequently used.

Another reason I didn't do it that way originally is that we used to be able to emit the entry chunks from ember-auto-import's `treeForVendor`, which was simpler and gets the source mapping correct. Unfortunately, ember-cli broke that during the "packager" refactor by introducing a huge number of spurious broccoli graph edges that make ember-auto-import's case into a cycle (even though there' no real cycle). The tl;dr is, if you combine a ton of broccoli trees only to pull them apart again later, you just entangled the broccoli dependency graph in a bad way.

**Comment by rwjblue** [comment]
I believe this is fixed in ember-auto-import@2

**Comment by ef4** [comment]
Yes, this is fixed in 2.0, where we went with the strategy mentioned above of not concatenating the webpack chunks onto vendor.js.
