### ISSUE TITLE
Ability to build from dependency's src directory

### ISSUE THREAD

**Issue by taras** [ef4/ember-auto-import#32]
Libraries that primarily target ecosystems other than Ember, usually transpile their ES builds to target the browsers they support. For example, if the library supports IE11 the modules build will transpile classes. 

The problem arises when babel transpiled class tries to extend a native class, it throws this error: `Class constructor User cannot be invoked without 'new'`.

Since EmberCLI knows the browser requirements for each app, we can skip the bundled modules by going directly to the src directory. It won't be the right solution for all modules but it will for some like `microstates`.

Is it possible for me to configure `ember-microstates` to tell `ember-auto-import` to build from `src` directory that's included in the npm package?

**Comment by ef4** [comment]
In terms of offering optional un-transpiled source, I think you can already do that by setting `module` in package.json. When building with ember-auto-import the modules will take precedence over the normal `main`, which allows you to ship both untranspiled modules and prebuilt scripts. 

Then the second piece would be running the imported code through your app's existing babel config. Right now we don't, as it seems like a pretty expensive operation when most libraries don't need it.

But we do already offer a way to extend the webpack config from inside your app (or addon). It should be possible to turn on the webpack babel plugin, in order to experiment with this. If it turns out to be a popular option, we can make it more convenient, particularly by making it easier to match the same babel settings as the host app (there is already code in ember-auto-import for doing that, since we need to configure the babel parser to match what syntax is allowed in the app).

**Comment by taras** [comment]
> In terms of offering optional un-transpiled source, I think you can already do that by setting module in package.json.

In React ecosystem, most apps are configured to not transpile content of node_modules, as a result the module entry has to be transpiled for browser you support. In microstates, module points to a file that's transpiles classes but leave imports intact to allow tree shaking. 

> Then the second piece would be running the imported code through your app's existing babel config. Right now we don't, as it seems like a pretty expensive operation when most libraries don't need it.

I suspect that once you going down the path of using `module` entry, the ability to transpile using app's build rules will be come more important. 

> match the same babel settings as the host app (there is already code in ember-auto-import for doing that, since we need to configure the babel parser to match what syntax is allowed in the app).

Is it possible for me to use this? I'd like to use the app's settings to transpile the contents of src directory in node_modules

**Comment by ef4** [comment]
It's definitely possible to extend the webpack config from an app. I haven't tested doing it from an addon, but that should work too (in general, addons need to put this kind of config in index.js, apps put it in ember-cli-build.js).

From an app it looks like:

```
  let app = new EmberApp(defaults, {
    autoImport: {
      modules: {
        microstates: {
          webpackConfig: {
             // stuff in here will get merged into the webpack config when we're bundling microstates
          }
        }
      }
    }
```

I deliberately haven't documented this option yet, it's possible I will need to break its meaning slightly when I make ember-auto-import run webpack exactly once per app (as opposed to running per external package). But you should feel free to experiment and your feedback will help me shape the API.

**Comment by taras** [comment]
@ef4 We actually ended up changing microstates to make this unnecessary. Thank you very much for your help and your time.

**Comment by bummzack** [comment]
Sorry for hijacking this thread. I was looking for a way to turn on code transpiling and found this:

> Then the second piece would be running the imported code through your app's existing babel config. Right now we don't, as it seems like a pretty expensive operation when most libraries don't need it.

Would it be possible to get an example for this? I'd like to transpile an imported library with the same setting as main main ember app (eg. for browsers defined in `config/targets.js`)
