### ISSUE TITLE
Webpack configuration duplicated for main app

### ISSUE THREAD

**Issue by kobsy** [ef4/ember-auto-import#349]
I've run into an issue that I _think_ is something to do with `ember-auto-import`, but I've been having trouble tracking down the reason for the behavior.

The short version is, when I include a particular addon, the webpack configuration in my application's `ember-cli-build.js` is duplicated, running resources through the given plugins/loaders twice.

So why am I here instead of on the addon's Issues? Because I'm also the addon author! 😅 The addon is https://github.com/cph/ember-help-widget/ (it's a simple help widget used by my company's products; we opted to leave it public, since it didn't contain any sensitive logic/information, but didn't think it broadly useful enough to publish on NPM/advertise as an Ember addon for wider usage), and I don't think I'm doing anything out-of-the-ordinary. FWIW, `ember-auto-import` is a dependency of the addon as well as the main app.

I was able to reproduce the issue with this proof-of-concept app consuming the above addon: https://github.com/kobsy/ember-double-auto-import . The application has one, currently-unneeded webpack rule for demonstration purposes.

When I run `ember build` with `DEBUG="ember-auto-import:bundler"` for the proof-of-concept, the output is 
```
ember-auto-import:bundler extraWebpackConfig {"module":{"rules":[{"test":{},"use":["raw-loader"]},{"test":{},"use":["raw-loader"]}]}}
```

Digging into it, the sequence I observed is something like:
1. The leader `AutoImport` is initialized and pointed at the "topmost" addon, the package of which is the top-level app.
2. That package is added to `this.packages`
3. The registry callback registered with `setupPreprocessorRegistry` calls `analyze()` on the copy of the addon added to the top-level app, as well.
4. Somehow, this second copy points at a different object (still describing the same top-level app, but distinct as far as `Set()` is concerned), which is also added to `this.packages`
5. The top-level app is effectively in `this.packages` twice, doubling up its webpack config.

The part I'm stumped on is step 4 above. Without digging into broccoli internals, I'm not sure how/why the second copy of the addon is pointing at a different "package" object representing the main app. And I'm definitely not at all sure what it is about this addon in particular that's causing the problem to occur in the first place. 😖 

Any insight on this would be much appreciated, especially if there's just something I'm missing with the way `ember-auto-import` works. I'd be happy to answer whatever questions I can on my end, as well. 🙂 

Thanks for an incredible, indispensable addon! 😁

**Comment by bendemboski** [comment]
I'm seeing this as well, and have diagnosed the problem, but I'm not sure what the solution is.

I have an app that has its own copy of `ember-auto-import`, and also a bunch of addons that have their own copies, except they all have compatible versions and resolve to the same instance of the `ember-auto-import` node module in the filesystem (not sure if that matters or not). So let's say I have `my-app` which depends on both `ember-auto-import` and `my-addon`, and `my-addon` also depends on `ember-auto-import`.

When my build runs, the [leader chooser](https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/auto-import.ts#L35) picks the `ember-auto-import` instance that's the child of `my-addon` for some reason, rather than the one that's the child of `my-app`. So the [topmost addon](https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/auto-import.ts#L44) ends up being `my-addon`, and we create a package instance representing `my-app`, but [cache-keyed](https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/package.ts#L66) by `my-addon`.

Then we [analyze](https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/auto-import.ts#L61) all the various `ember-auto-import` instances, and eventually reach the one that's a child of `my-app`. When we [look up its parent](https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/auto-import.ts#L62), we get back a package representing `my-app`, but not the same package object as we previously created for `my-app` because that one was cached under `my-addon`, not `my-app`'s `ember-auto-import` instance. So we create a new package object with exactly the same data (including webpack config) and add it to `this.packages`, and then later when we merge it all together the webpack config gets duplicated.

**Comment by ef4** [comment]
Nice, thanks for digging in. That should make this straightforward to fix.

**Comment by bendemboski** [comment]
For anyone that needs a temporary workaround, I managed to do so by:

1. Creating an in-repo addon whose `index.js` has the `options.autoImport.webpack` config that my app needs (and removing it from the app's `ember-cli-build.js`)
2. Create an empty `addon` folder in the in-repo addon (with a `.gitkeep` file) so the in-repo addon's `treeForAddon()` won't no-op, and will process its nested addons
2. Add `ember-auto-import` and `ember-cli-babel` to its dependencies (`ember-cli-babel` is needed so `ember-auto-import` finds it [here](https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/package.ts#L129-L130) and doesn't blow up)

This will cause the webpack config to be merged into the full webpack config, but not get duplicated because it's coming from an addon rather than the top-level app, so won't trigger this issue.
