### ISSUE TITLE
Plans to publish new version?

### ISSUE THREAD

**Issue by shamrt** [ef4/ember-auto-import#351]
Any plans to publish a new version soon? My team is *very* interested in the `watchDependencies` option (#350) that was just merged to `master`. 

Thanks, and love your work!

**Comment by shamrt** [comment]
Question: Any reason watch can't be used with addons? i.e. is there a specific reason?

**Comment by buschtoens** [comment]
> Question: Any reason watch can't be used with addons? i.e. is there a specific reason?
> 
> Nb. [#350 (files)](https://github.com/ef4/ember-auto-import/pull/350/files#diff-407d6d89cf0b6b066c2c93c471a0e30a8eea5fce1d67b49e7dac9130e589656eR311-R312)

I guess the reason is that you would not want third-party addons to register watchers. If, for instance, the addon author has forgotten to remove this setting, installing the addon in your app would consume unnecessary resources by needlessly watching directories.

During addon development you can set the `watchDependencies` config in the `ember-cli-build.js` file of the addon. If you're working in a monorepo and want to watch dependencies, you would have access to the root app's `ember-cliu-build.js` file as well and could set it there.

**Comment by ef4** [comment]
Yes, it's the person running the app who knows which libraries they really intend to edit. The addons don't know and shouldn't try to guess. An addon's dummy app of course is free to setup watches if you need them while developing the addon.

Also keep in mind that ember-auto-import only handles packages that are not ember addons. Watching of ember addons is different and has its own system. (That distinction is going to get smaller as we ship Embroider v2 Addon support -- those *will* be handled by ember-auto-import in non-embroider builds.)

**Comment by shamrt** [comment]
Makes sense, thank you! 

On the question of a future release, is the package currently in a state where that's feasible?

**Comment by shamrt** [comment]
> On the question of a future release, is the package currently in a state where that's feasible?

Sorry to be a bother. Is there a new release inbound, or are you waiting on something? The project doesn't use milestones, so it's difficult to tell. 

My team would _really_ like to use `watchDependencies` 🙂

**Comment by ef4** [comment]
Released 1.11.0.
