### ISSUE TITLE
Unable to use Webpack Loaders

### ISSUE THREAD

**Issue by josemarluedke** [ef4/ember-auto-import#427]
It seems we cannot use Webpack loaders with Ember Auto Import v2. 

The expected behavior is that adding a Webpack loader would allow us to import other type of files without any issue.

My use case is importing GraphQL files (`.graphql`) using `graphql-tag/loader`. 

I have a reproduction app here: https://github.com/josemarluedke/--auto-import-webpack-loader

This is the configuration for Ember Auto Import: 

```js
autoImport: {
      webpack: {
        module: {
          rules: [
            {
              test: /\.(graphql|gql)$/,
              exclude: /node_modules/,
              loader: 'graphql-tag/loader',
            },
          ],
        },
      },
    },
```

The error is: 

```
Error: Could not find module `auto-import-webpack-loader/gql/query.graphql` imported from `auto-import-webpack-loader/routes/index`
```

**Comment by ef4** [comment]
Thanks for making a reproduction.

Your problem is not the loader, it's that you're trying to auto-import from within your own app. That is not supported. ember-auto-import only deals with third-party packages. To run webpack over your app itself, you need Embroider.

The easiest workaround is to move the queries into an in-repo addon. The addon must be in v2 format, because ember-auto-import ignore classic addons, because classic addons have their own complicated logic for how their code gets into the build.

Here is a PR demonstrating it working in your reproduction: https://github.com/josemarluedke/--auto-import-webpack-loader/pull/1
