### ISSUE TITLE
Allow import of inner modules

### ISSUE THREAD

**Issue by jeanduplessis** [ef4/ember-auto-import#7]
First off thank you for taking the effort to write this addon.

I'm trying to move from using ember-browserify, and all my imports work except Firebase.

package.json:
```
"devDependencies": {
  ...
  "firebase": "5.0.4",
  ...
}
```

in my code as per Firebase's instruction here: https://www.npmjs.com/package/firebase#include-only-the-features-you-need 
```javascript
import firebase from 'firebase/app';

// These imports load individual services into the firebase namespace.
import 'firebase/messaging';
```

When I run the app I get the following error: `Error: Could not find module 'firebase/app' imported from 'samewave-client/services/browser-push-notifications'`.

**Comment by ef4** [comment]
We need to add support for importing inner modules from within packages.

In practice it's just necessary because node supports it, so people expect it to work, so library authors design APIs that need it.

(In a perfect world, I would rather we didn't support this, because it's better to have package authors explicitly expose their public API via the package's main entrypoint. But that ship has sailed.)

**Comment by jeanduplessis** [comment]
Not sure this is an ember-auto-import issue anymore but as an FYI the importing of firebase/app and firebase/messaging didn't work with 0.2.2 for me. 
It doesn't add the messaging function to the firebase app prototype. 

I can see it defines the modules in vendor.js for firebase/app and firebase/messaging.

**Comment by ef4** [comment]
If you can share a reproduction I will be happy to take a look.

**Comment by jeanduplessis** [comment]
@ef4 thanks, I'll create a new ember project later that showcases the issue and submit as a new issue.
