### ISSUE TITLE
Can't get ember-highcharts work

### ISSUE THREAD

**Issue by kasunvp** [ef4/ember-auto-import#73]
I tried importing highcharts dynamically and it is working. 
But when I tried importing `ember-highcharts` it is giving the following error.

![ember-highcharts-import](https://user-images.githubusercontent.com/56943/43154902-7f71f304-8f93-11e8-8a82-2dbd423c91bf.png)

**Comment by ef4** [comment]
Hi. ember-auto-import purposely ignores other ember addons because they already include themselves into the application. 

You can import highcharts (not ember-highcharts) directly. If you want to use the components provided by ember-highcharts with a dynamically-imported copy of highcharts, you will need to make a PR to ember-highcharts to make it use ember-auto-import directly.

**Comment by ef4** [comment]
Making is easy to import other ember addons and components is part of the next phase of my world domination plan.

**Comment by kasunvp** [comment]
We actually have some in-house addons that provide components, are fetched from private github repos. As the same error happened with them, I tried with the `ember-highcharts` coming from npm repository. 

So I suppose `ember-auto-import` doesn't work yet with ember addons with components, right?

**Comment by ef4** [comment]
Correct. Right now it's a bit awkward to lazy load ember components.

**Comment by ncoden** [comment]
Hi @ef4 :wave:. Did you had a chance to look at the lazy loading of ember components ?

**Comment by ef4** [comment]
That is a core feature of [embroider](https://github.com/embroider-build/embroider). ember-auto-import can be viewed as a partial polyfill for embroider.

To manage components, we need to have global visibility and control into the whole dependency graph, so it really does require adopting a new build pipeline like embroider.
