### ISSUE TITLE
Redirect some / all modules to a different output file?

### ISSUE THREAD

**Issue by peterjmag** [ef4/ember-auto-import#79]
Is it possible to configure ember-auto-import in such a way that certain modules are redirected to a different output file?

A bit more about my particular use case, if it's helpful: I'm working on a reasonably large Ember app, and we're experimenting with some new modules that we don't want to deliver to all users as part of the `vendor.js` bundle yet. (Currently, the experimental stuff is switched on for a small number of users via a feature flag.)

Ideally, the generated bundles would look something like this:

```
/assets/experimental.js
(The experimental bundle delivered to users with the feature flag turned on.)
  - react
  - react-dom
  - classnames
  - react-copy-to-clipboard 
  - ...and other npm modules that are only consumed by React components

/assets/vendor.js
(The standard vendor bundle delivered to everyone.)
  - url-regex
  - pikaday
  - psl 
  - ...and other npm modules that we use in Ember
```

I've been experimenting with customizing the webpack config [as per the readme](https://github.com/ef4/ember-auto-import/blob/3216740762741e4539dc20382e17c8edd4d24412/README.md#customizing-build-behavior), but as far as I can tell, the output from that is just an intermediate step before it gets added to the normal vendor bundle.

Any ideas? Thanks in advance!

**Comment by ef4** [comment]
This is a good use case for dynamic import.

You would put all your experimental stuff into a separate package. It doesn't need to be real published NPM package, but it does need to be able to be resolved like one during your build, so you could do something like:

```
devDependencies: {
  "experimental": "file:./experimental"
}
```

and create `./experimental/package.json`, `./experimental/index.js`, etc. Let it be the real entrypoint for your experimental code, including both your own components and their dependencies.

Then in some place like your application route you can wait until experimental is loaded:

```
beforeModel() {
  return this.maybeLoadExperimental();
},
maybeLoadExperimental() {
  if (featureFlagEnabled) {
    return import('experimental');
  } else {
    return Promise.resolve();
  }
}

```

The reason I'm suggesting a separate package is due to the way ember-auto-import decides what things are eligible for it to include. It doesn't try to import modules that are inside ember addons or ember apps, because those generally already have their own conventions for how they get into the build and we don't want to double-include anything.

**Comment by peterjmag** [comment]
Thanks @ef4! Agreed, seems like dynamic imports make a lot of sense here. I'll give it a try!
