### ISSUE TITLE
auto-imported dependency from add-on not available to parent app

### ISSUE THREAD

**Issue by sfbwalder** [ef4/ember-auto-import#84]
This may be continuation of #2 with a different example - yadda and ember-cli-yadda.

Addon ember-cli-yadda is using ember-auto-import to include yadda.  The acceptance tests in this addon can `import yadda from 'yadda'`.  But, an app that consumes ember-cli-yadda cannot import yadda from its acceptance tests.  

Should yadda be available to a parent app's acceptance tests as it is to ember-cli-yadda's acceptance tests?

Ember 3.x is being used in addon and parent app.

Here are some config and debug output details:

```
// ember-cli-yadda package.json
  "dependencies": {
    // some things removed
    "ember-auto-import": "^1.2.5",
    "yadda": "*"
  },
```

Debug output when run `ember s` for ember-cli-yadda addon:

```
2018-07-31T19:41:22.235Z ember-auto-import:splitter output {
  "app": {
    "static": [],
    "dynamic": []
  },
  "tests": {
    "static": [
      {
        "specifier": "yadda",
        "entrypoint": "C:\\dev\\ember\\ember-cli-yadda\\node_modules\\yadda\\lib\\in                                                  dex.js",
        "importedBy": [
         {
            "package": "ember-cli-yadda",
            "path": "dummy/tests/acceptance/steps/steps.js",
            "isDynamic": false
          },
        // many more removed
    ],
    "dynamic": []
  }
}
```

Debug output when run `ember s` for parent app (note uri.js being pulled in from another addon using auto import):
```
2018-07-31T20:31:00.949Z ember-auto-import:splitter output {
  "app": {
    "static": [
      {
        "specifier": "urijs",
        "entrypoint": "C:\\dev\\ember\\parent-app\\node_modules\\urijs\\src\\URI.js",
        "importedBy": [
          {
            "package": "ember-env-urls",
            "path": "ember-env-urls/utils/sf-url.js",
            "isDynamic": false
          }
        ]
      }
    ],
    "dynamic": []
  },
  "tests": {
    // why aren't references to yadda from the parent app's acceptance tests listed here?
    "static": [],
    "dynamic": []
  }
}
```

**Comment by ef4** [comment]
This is intentional. ember-auto-import only allows the app to `import` things that appear in the app's own `dependencies` or `devDependencies`. This follows node_modules resolution rules.

The addon (ember-cli-yadda) _can_ import the library (yadda), and if it does that pulls the library into the build, and as a side-effect that allows anything in the app to use it. That's because once we're at runtime in the browser, we're back to normal loader.js conventions, which has a flat namespace of AMD modules, where anything can import anything else. _But I would break that right now if i could, because it's a bad pattern_.

It's a bad pattern because

1. Human readers of `import "yadda"` should be able to easily tell what package that is actually referring to.
2. Build tools and editors should be able to look at `import "yadda"` and statically know which exact module on disk is being talked about, so they can do smart builds or offer smart static analysis.

The rule I want to suggest here is that if your package is named "ember-cli-yadda", telling people to import from anything other than "ember-cli-yadda" is a megatroll.

So the path forward for an addon that does this is:

 - If the addon exists only to pull in the underlying library, the addon should be deprecated, and people should be told to just ember-auto-import the underlying library directly.
 - If the addon builds extra ember-specific stuff on top of the library, that's good, but if you also want to offer the underlying library for apps to `import`, you should either
    1. reexport it under your own namespace. So apps would do `import { yadda } from 'ember-cli-yadda'`.
    2. or make the underlying library a peerDependency of your addon. You can still use ember-auto-import to access it from your addon, and the app can also use ember-auto-import to access it directly. In this case you would need to tell people to add the library directly to their own dependencies (or do that for them in a blueprint).

**Comment by sfbwalder** [comment]
Thank you for the great explanation!
