### ISSUE TITLE
Cannot import microstates

### ISSUE THREAD

**Issue by knownasilya** [ef4/ember-auto-import#9]
Here are it's main (etc) definitions https://github.com/microstates/microstates.js/blob/master/package.json#L21

I'm doing this in an addon for the dummy app. The module is installed and in `devDependencies`. I get the following error:

> Uncaught Error: Could not find module `microstates` imported from `ember-microstates/components/state-for`

The code with the import is here https://github.com/knownasilya/ember-microstates/blob/update/addon/components/state-for.js#L3

**Comment by ef4** [comment]
I think this is the same as #7

**Comment by ef4** [comment]
Oh wait, nevermind, I misread that were trying to import `ember-microstates/components/state-for`, but that is the source of the import.

**Comment by knownasilya** [comment]
@taras and I paired and fixed some of the build stuff so I'll give it another try to see if that made a difference, since regular `import()` works now.

**Comment by taras** [comment]
@ef4 it would be great if it was possible to import from `module` because that's what we test against with jest. It would ensure that the dependency that's used by this library is always tested for. Right now, we're using UMD which has all dependency recompiled but this library might be the only one using it.

**Comment by ef4** [comment]
I think this is fixed as of 0.2.2.
