### ISSUE TITLE
jQuery plugins

### ISSUE THREAD

**Issue by evoactivity** [ef4/ember-auto-import#93]
Let's say I have a very simple component like so

```javascript
import Component from '@ember/component';
import 'justifiedGallery';

export default Component.extend({
  didInsertElement(){
    this._super(...arguments);
    this.$().find('.gallery').justifiedGallery();
  }
});
```

What I'd expect is that the imported justifiedGallery has added itself to jquery and the component could then use it, but what appears to happen is webpack is creating it's own bundled version of jquery and the plugin is being added to that, and I have no access to that jquery from my component.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/83799/43732892-c7c6503e-99aa-11e8-80ca-dd5ee7ed57f2.png">

**Comment by ef4** [comment]
Thanks for reporting this. I just added a solution to this [to the readme](https://github.com/ef4/ember-auto-import#im-trying-to-load-a-jquery-plugin-but-it-doesnt-attach-itself-to-the-copy-of-jquery-thats-already-in-my-ember-app).

**Comment by yads** [comment]
I know this issue is closed, but I ran into an odd issue with jquery interference and hopefully this comment might help someone else. I followed the instructions of adding the webpack externals options which did not seem to help. The issue turned out to be the fact that I had both `@ember/jquery` and `jquery` in my package.json. Once I removed the regular `jquery` from my package.json things worked just as they should.
