### ISSUE TITLE
when used in an addon to wrap a library, will consuming apps be able to import that library

### ISSUE THREAD

**Issue by tomwayson** [ef4/ember-auto-import#95]
I've got an addon that acts as a wrapper for a library by `app.import()`ing and shimming that library. So, although my library wraps many of the functions from the library, the shim acts as an escape hatch so that consuming apps can `import { unwrappedFunction } from 'wrapped-library'`.

I am guessing that using ember-auto-import in an addon would handle all `import`s of `wrapped-library` w/in the addon itself, but would not handle any such imports in consuming apps. I'm also guessing it would not "auto-shim" the library so that consuming apps could `import` any of it's unwrapped functions. Is that right?

**Comment by ef4** [comment]
This is a similar question to what I answered here: https://discuss.emberjs.com/t/best-practices-for-including-3rd-party-libraries-in-an-addon/15200/2?u=ef4

It turns out that as an accident of how ember's loader already works and the fact that we interoperate with it, consuming apps _can_ actually import anything that your addon already imports. But I don't think this is a particularly good idea to tell people to rely on.

In general, I want anyone writing `import from "thing"` to have "thing" in their own deps in package.json. Anything else is weird and hard to analyze both for humans and machines.

I think you have two good options: 
 - reexport the original library under your own addon's namespace. Then there is nothing weird, and when the app wants to access those functions, it's clear that it's getting them via you: `import { unwrappedFunction } from "your-addon/wrapped-library";`
 - make the library a peerDependency of your addon and use a blueprint to add it directly to the app's devDependencies. This still allows it to be auto imported from your addon. And then if people want to access the library directly, they just add `ember-auto-import` to their app at which point they can access the library normally, since it's already one fo their own dependencies.

**Comment by ef4** [comment]
The first option is more self-contained and less intrusive to the app. The second option has the benefit of letting them pick a wider range of versions of the underlying library.
